# Default values for innovative-school
# This is a YAML-formatted file.

replicaCount: 1

image:
  repository: ghcr.io/your-username/innovative-school
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
  hosts:
    - host: innovativeschool.cm
      paths:
        - path: /
          pathType: Prefix
    - host: api.innovativeschool.cm
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: innovative-school-tls
      hosts:
        - innovativeschool.cm
        - api.innovativeschool.cm

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Backend configuration
backend:
  enabled: true
  replicaCount: 3
  image:
    repository: ghcr.io/your-username/innovative-school-backend
    tag: "latest"
    pullPolicy: IfNotPresent
  
  service:
    type: ClusterIP
    port: 8000
  
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi
  
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80
  
  env:
    DATABASE_URL: "postgresql://postgres:password@postgresql:5432/innovative_school"
    REDIS_URL: "redis://redis:6379/0"
    ENVIRONMENT: "production"
    CORS_ORIGINS: "https://innovativeschool.cm,https://www.innovativeschool.cm"
  
  secrets:
    SECRET_KEY: "your-secret-key-here"
    JWT_SECRET_KEY: "your-jwt-secret-key-here"
    GOOGLE_MAPS_API_KEY: "your-google-maps-api-key-here"
    AWS_ACCESS_KEY_ID: "your-aws-access-key-id-here"
    AWS_SECRET_ACCESS_KEY: "your-aws-secret-access-key-here"

# Frontend configuration
frontend:
  enabled: true
  replicaCount: 2
  image:
    repository: ghcr.io/your-username/innovative-school-frontend
    tag: "latest"
    pullPolicy: IfNotPresent
  
  service:
    type: ClusterIP
    port: 80
  
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
  
  env:
    REACT_APP_API_URL: "https://api.innovativeschool.cm"
    REACT_APP_GOOGLE_MAPS_API_KEY: "your-google-maps-api-key-here"
    REACT_APP_ENVIRONMENT: "production"

# PostgreSQL configuration
postgresql:
  enabled: true
  auth:
    postgresPassword: "secure_password_here"
    database: "innovative_school"
  primary:
    persistence:
      enabled: true
      size: 20Gi
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi

# Redis configuration
redis:
  enabled: true
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
      size: 8Gi
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi

# Nginx Ingress Controller
nginx-ingress:
  enabled: true
  controller:
    service:
      type: LoadBalancer
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi

# Monitoring
monitoring:
  enabled: true
  prometheus:
    enabled: true
    server:
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 250m
          memory: 512Mi
  
  grafana:
    enabled: true
    adminPassword: "admin123"
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi

